# Generated by Django 5.1.1 on 2024-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_asia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourasia',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
    ]
